############################################################
# Launcher for STATegraEMS container for the eBioKit
# This is a template, the following values must be replaced:
#   - $$APP1_PORT$$, port number for the Galaxy instance
#   - $$MYSQL_ROOT_PASSWORD$$, the password for the mysql root account
#   - $$DATA_LOCATION$$, location for the application data
# TODO:
# - Tomcat logs
############################################################

version: '2'
services:

    stategraems_machine:
      image: ebiokit/stategraems
      container_name: stategraems_machine
      links:
        - stategraems_db:stategraems-mysql
      depends_on:
        - stategraems_db
      volumes_from:
        - stategraems_data
      ports:
        - "$$APP1_PORT$$:8080"

    stategraems_db:
      image: mysql
      container_name: stategraems_db
      environment:
        - MYSQL_ROOT_PASSWORD=$$MYSQL_ROOT_PASSWORD$$
      depends_on:
        - stategraems_data
      volumes_from:
        - stategraems_data

    stategraems_data:
      image: busybox
      container_name: stategraems_data
      volumes:
        - $$DATA_LOCATION$$/var/lib/mysql:/var/lib/mysql
        - $$DATA_LOCATION$$/data:/data
